apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: __APP_NAME__
    group: __GROUP_NAME__
  name: __APP_NAME__
  namespace: __NAMESPACE__
spec:
  progressDeadlineSeconds: 600
  replicas: __REPLICAS__
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: __APP_NAME__
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: /__PROJECT_NAME__/metrics
      labels:
        app: __APP_NAME__
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
               - key: group
                 operator: In
                 values:
                 - __GROUP_NAME__
      imagePullSecrets:
        - name: vpsecret
      containers:
        - name: lvdl-fe
          image: 'docker.vpgame.cn/__PROJECT_NAMESPACE__/__PROJECT_NAME__:__VERSION__'
          command: ["/bin/sh", "-c", "npm run start"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1024m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: 1024m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
