apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: __APP_NAME__
    group: __GROUP_NAME__
  name: __APP_NAME__
  namespace: __NAMESPACE__
spec:
  progressDeadlineSeconds: 600
  replicas: __REPLICAS__
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: __APP_NAME__
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: /__PROJECT_NAME__/metrics
      labels:
        app: __APP_NAME__
    spec:
            #affinity:
            #nodeAffinity:
            #requiredDuringSchedulingIgnoredDuringExecution:
            #nodeSelectorTerms:
            #- matchExpressions:
            #- key: group
            #operator: In
            #values:
            #- __GROUP_NAME__
      imagePullSecrets:
        - name: vpsecret
      containers:
        - name: label-system-fe
          image: 'docker.vpgame.cn/__PROJECT_NAMESPACE__/__PROJECT_NAME__:__VERSION__'
          command: ["/bin/sh", "-c", "npm run start"]
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: 250m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 1024Mi
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /opt/google_auth/conf/google_auth.json
            - name: NODE_ENV
              value: development
          volumeMounts:
            - mountPath: /opt/google_auth/conf
              name: google-auth-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: google-auth-volume
        configMap:
          name: clips-uploader
          items:
          - key: us-team-testing-env.json
            path: google_auth.json

