export const SET_UPLOADED_IMAGES = 'SET_UPLOADED_IMAGES'

export const GET_LABEL_IMAGES = 'GET_LABEL_IMAGES'

export const GET_LABEL_LIST = 'GET_LABEL_LIST'
export const GET_ALL_LIST_TYPES = 'GET_ALL_LIST_TYPES'

export const POST_UPLOAD_IMAGES = 'POST_UPLOAD_IMAGES'
export const POST_UPLOAD_LABELS = 'POST_UPLOAD_LABELS'

export const SET_SITE_LANG = 'SET_SITE_LANG'
export const SET_SITE_LANGUAGE = 'SET_SITE_LANGUAGE'

export const SET_CURRENT_DATA_SET = 'SET_CURRENT_DATA_SET'
export const REMOVE_COMPLETED_IMAGE = 'REMOVE_COMPLETED_IMAGE'