export const GET_PLAYER_ACHIEVEMENTS = 'GET_PLAYER_ACHIEVEMENTS'
export const GET_PLAYER_BADGES = 'GET_PLAYER_BADGES'
export const GET_PLAYER_CARDS = 'GET_PLAYER_CARDS'
export const GET_PLAYER_DECKS = 'GET_PLAYER_DECKS'
export const GET_PLAYER_MATCHES = 'GET_PLAYER_MATCHES'
export const GET_PLAYER_OVERVIEW = 'GET_PLAYER_OVERVIEW'
export const GET_PLAYER_TRENDS = 'GET_PLAYER_TRENDS'
export const GET_PLAYER_UPCOMING_CHESTS = 'GET_PLAYER_UPCOMING_CHESTS'

export const GET_LEADERBOARD_PLAYERS = 'GET_LEADERBOARD_PLAYERS'
export const GET_LEADERBOARD_CLANS = 'GET_LEADERBOARD_CLANS'

export const GET_MATCHES_DETAIL = 'GET_MATCHES_DETAIL'

export const GET_CLAN_DETAIL = 'GET_CLAN_DETAIL'

export const GET_SEARCH_PLAYER = 'GET_SEARCH_PLAYER'

export const GET_GLOBAL_CARDS = 'GET_GLOBAL_CARDS'
export const GET_GLOBAL_DECKS = 'GET_GLOBAL_DECKS'

export const SET_SITE_LANG = 'SET_SITE_LANG'
export const SET_SITE_LANGUAGE = 'SET_SITE_LANGUAGE'

export const POST_ETL_PLAYERS = 'POST_ETL_PLAYERS'